### ISSUE TITLE
Backup drive

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#398]
Explore local and remote backup options

**Comment by adelavega** [comment]
We may be able to backup to corral with a bash script as well

**Comment by adelavega** [comment]
@rwblair do you have any input as to what backup solution we should use?

Options are:
1) SCP to corral-repl (replicated storage). This would only backup the data/folders, not the whole machine
2) UTBackup, which is Code42 CrashPlan. Specifically says not for server backups Need to be requested. It uses incremental diffs to backup your whole machinie
3) Box. Partial backup in the cloud through box.

**Comment by rwblair** [comment]
I'm a fan of SCP to corral-repl since its straightforward and easy to move around. Resetting up the site from this type backup wouldn't be too hard.

For full machine backup I'd consider having a local external hard drive and pulling images with something like this: http://www.fsarchiver.org/live-backup/

I have crashplan running on my desktop but don't have any experience restoring from it.

Box is ok, but I still prefer anything that can be done through cli over a web interface. (I'm sure there's a box cli but scp is on any and every machine well touch.)

**Comment by adelavega** [comment]
Cool, lets go w/ scp to corral then!

**Comment by adelavega** [comment]
I've backed up the `/neuroscout-data` folders and `/www` folders to `corral-repl`
