### ISSUE TITLE
Browsing predictors slow with 1000+ predictors

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#470]
I extracted over 1500 predictors on studyforrest, mainly from GoogleVisionAPILabelDetection. Unfortunately, this makes the frontend really laggy. In the meantime, I'll disable these predictors (or only include a subset of predictors), but in the long run we need to do some profiling and see what's casuing the issue (it's a lot of predictors but not *that* many).

**Comment by tyarkoni** [comment]
I think we should make this a high priority—a large predictor library is going to be a major selling point for the project.

What's the main bottleneck? Is it retrieving data from server, loading it into the table the first time, or updating results in real-time based on user input?

I'm thinking this might be the point in time at which we need to switch from client-side filtering to server-side filtering...

**Comment by adelavega** [comment]
I agree. That said, I still it's a decent idea to curate which predictors are shown. In the past we did this by only extracting common Clarifai predictors. I think culling the number of Google Labels to those that appear in a certain percentage of volumes would be useful.

**Comment by adelavega** [comment]
But still, even with this many predictors, frontend filtering should still be OK. We're not talking millions or hundreds of thousands

**Comment by rwblair** [comment]
Playing around with it enabling pagination makes everything more responsive. This works because it limits the number of rendered items to just those on that page of the table. 

I can wrap the select predictors in a conditional so that it is only rendered when we are on the predictors tab, and unmounted when we leave that tab. This makes everything but the predictors tab work normally, and allows us to keep using no pagination. I'll keep looking and see what else can be done to make the full list work as quickly as we'd like.

Browsing antd issues I found reference to this, it only renders parts of list that are visible to user so it might be a way forward:
https://github.com/bvaughn/react-virtualized

**Comment by adelavega** [comment]
Cool. I don't mind pagination too much if that fixes our problem... Although the infinite scroll is nicer

**Comment by rwblair** [comment]
I tested the big table package for react, react-table, and it was still slow when attempting to render all elements on a large numbers of predictors.

As a compromise (#523) I enabled pagination and set page size to 200, this should let most datasets display all their predictors on one page. @adelavega let me know if this seems performant enough.

**Comment by adelavega** [comment]
I think that's a good compromise for now! Closed with #523
