### ISSUE TITLE
Add acknowledgment of NeuroVault upload to terms of use

### ISSUE THREAD

**Issue by tyarkoni** [neuroscout/neuroscout#532]
We need to add a bullet to the list of terms of use that goes something like:

"I understand that the statistical maps generated by this analysis will be automatically uploaded to the NeuroVault website (though they will not be publicly accessible unless the analysis is set to public on NeuroScout)".

I'm a little worried that this will deter people from using the service, at least in the early days, so we may want to think about disabling the automatic upload (or making it opt-in) until there's some traction. But I guess we can try this out at first and see how it goes.

**Comment by adelavega** [comment]
What if we force users to agree to have usage tracked, and state that by default stat maps are uploaded, but also allow users to opt out using the CLI. However, this would be tracked, so that we can see if this is a problem (e.g., a majority of users opting out). If so, we could change the policy to being mandatory.
