### ISSUE TITLE
improve predictor selection / search tab

### ISSUE THREAD

**Issue by rbroc** [neuroscout/neuroscout#695]
- Filter features by extractors (same filter option used for Runs in dataset selection tab)
- add link to pliers API reference for each Extractor (jump directly at extractor)
- maybe add explicit info on modality
- [ ] Come with descriptions of extractors and add to API

**Comment by adelavega** [comment]
Closing #625 as a dupe. 

> ... make it easier to discover Predictors using structured information ... add a "+" / "Advanced" search mode that expands below the full text search. This lets you select by source, modality **etc..**

> Alternatively, we could use the built in ant design filter functions (but only as an apply, and filter, versus synced with selection like in the run selector). 

This is probably the easiest thing to start out with

> Additional improvements:
> * Max out predictor selection to 50 max predictors
> * Clear all button for Predictors

**Comment by adelavega** [comment]
Direct link to the docs

**Comment by adelavega** [comment]
In + interface:
- Longer description and/or link to Pliers / Neuroscout docs
- Precomputed stats (#696)
- Are there NAs?

**Comment by jdkent** [comment]
+1 on this, @rbroc, you say it better.

**Comment by adelavega** [comment]
Need to do on backend: - add "n/a" designation and precomputed stats. 
Also possibly make parameters easily accessible as JSON

**Comment by adelavega** [comment]
Re-summary of improvements:
- `Description` column is currently not very informative and repetitive. Feature specific description could be longer and moved to inside the `expandable content`.  For example, AudioSet has longer more useful descriptions: https://github.com/audioset/ontology/blob/master/ontology.json
- Extractor level descriptions which are hoverable.
- Instead of adding "modality" column, instead add a `tags` which could include things such as `modalities`. For example for `AudioSet`: `audio` `extracted` `neuralnet`. fmriprep: `confound` `n/as`
- Tweak threshold for putting selected predictors below so that table is wider more often
- Adding filter to all columns (including tags).
- Adding "+" to show expandable content, which can include the longer descriptions, link to docs, precomputed stats (min/max, contains n/a) etc...
- Minor: Make checkbox narrower

Once this is all done, re-vamp the "tour" to highlight these changes. (i) is very hard to see. Maybe replace with a more in depth HTML based tooltip in BLUE with a question mark. 

Big idea, but not necessary:
- Tree hierarchy for table. Top level elements would be `Source`.

**Comment by adelavega** [comment]
Filter panel ideas:
- Add filter to the right, look at ebay and new egg for inspiration.
- The number of categories to filter on can be more than he number of columns show in table if we don't filter using the table filter. 
- Make table longer and maybe remove scroll bar and add pages? Currently theres a scroll bar + pages
- Potentially move Analysis Builder Tabs to top if necessary, but try first tweaking tolerances to see if everything fits

**Comment by adelavega** [comment]
Notes from lab meeting:
- Add selected predictors tab ("shopping cart")
- When you switch to new tab, all things are unchecked (put numbers in parantheses update)
- Remove tags from bottom right
- Parentheses items matching (updates on search)
- All unchecked  = all selected
- Default to all unchecked

**Comment by adelavega** [comment]
@rwblair let's make sure to address #865 in this PR as well. I think we could just change the (i) to a question mark in blue. Perhaps a button with `<QuestionOutlined />` icon.
