### ISSUE TITLE
Cannot run extract_features from doc

### ISSUE THREAD

**Issue by bpinsard** [neuroscout/neuroscout#748]
The README specifies to run 
`python manage.py extract_features /datasets/ds009 emotionalregulation graph.json`
But it crashes with:
```
Traceback (most recent call last):
  File "manage.py", line 94, in <module>
    manager.run()
  File "/usr/local/lib/python3.6/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/usr/local/lib/python3.6/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/usr/local/lib/python3.6/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "manage.py", line 79, in extract_features
    local_path, task, graph_spec, **json.loads(filters))
  File "/neuroscout/neuroscout/populate/extract.py", line 185, in extract_features
    results = _extract(extractors, stims)
  File "/neuroscout/neuroscout/populate/extract.py", line 55, in _extract
    for name, parameters in extractors:
ValueError: not enough values to unpack (expected 2, got 1)
```

From the code the json file is never loaded and the filename ends up to be given to that for loop.
Is the doc wrong?
What is the difference between the graph and the filters?

It seems from the code that the [call to populate.extract_features in manage.py](https://github.com/neuroscout/neuroscout/blob/master/manage.py#L78) does not match the [function specs](https://github.com/neuroscout/neuroscout/blob/01cfcf46db8971a7afe1f15036093395342578c2/neuroscout/populate/extract.py#L174) and that filters ends-up not being used.

I am a bit lost, thanks for your help.

**Comment by adelavega** [comment]
Hey, there's a very good chance the docs are wrong!

To give more background, this is the full neuroscout app for the neuroscout.org web server. 
Although I documented it so that others can start local instances of this server, as well as for our own documentation purposes, it has largely been used internally to prop up that specific server (by me).
It also up so that if there are bugs to the neuroscout web server, others can fix it.

That's not to discourage you, but so you know there will be a few other issues like this (that I'm happy to fix because it improves our documentation).
 
For local feature extraction, are you familar with pliers? https://github.com/tyarkoni/pliers
That is what we use internally and is developed with a user-friendly API, and with the intention of public use.

As to this question, I have switched to primarily using `python manage.py ingest_from_json`, which I point to a config file such as those in `neuroscout/config/datasets/*`.

Those set up the extraction for a specific dataset, and allow me to set up custom meta-data, etc... 

Let me know if that's useful... I'm happy to provide more detail once I know a bit more about what you're trying to accomplish.

**Comment by bpinsard** [comment]
Thanks for your help and sorry to bother with bugs.
I understand that this as not been used by many other people which is why I tripped on a few bugs, and I am just posting issues as a way to contribute. 

We are interested in using neuroscout/pliers to provide annotated stimuli with an open-dataset. I wasn't sure where the boundary was between the two, but now I understand that neuroscout is more like a stack of services to provide online analysis definition.
We decided to look into neuroscout rather than pliers because I thought that it managed the storage of the features in the BIDS dataset, but from what I saw, extracted features are stored in a postgres database, as it is more convenient and faster for the web app.

I will look into how pliers can dump the extracted features to files, as we intend to distribute them with the dataset, and likely provide an API to access them to feed into deep-learning models.
I will also try the ingest_from_json option if we decide later to deploy a neuroscout instance for the project.

**Comment by adelavega** [comment]
Hey, no problem at all.

I think you have the distinction between pliers/neuroscout right. Features are stored in a postgres db, and served via a restful API for the web app. 

I think it would be a bit "heavy" for your use case, and not exactly what you're looking for.

I would agree that looking into pliers would be most useful. Perhaps it would be useful to contribute some scripts to wrap pliers and apply it to a BIDS dataset (outputting features back to the dataset itself).

The main thing is to produce BIDS event files with timing relative to the scan, versus relatively to the stimulus. That is, if the stimulus (e.g. video), is presented at 5s, you would want to offset the onsets that pliers returns to you (which are relatively to the start of the video), by 5 seconds so they align with the imaging timing.

Neuroscout does this internally, but its a bit convoluted because we store the extracted features relative to the stimulus, and only reconstruct the imaging timing on the fly when users request it via the API. Maybe looking at the ingestion scripts from neuroscout can help get you an idea of what is necessary (although it doesn't need to be as complicated).

Let me know if you have any other questions! We are very much interested in encouraging pliers/neuroscout/pybids use.

**Comment by adelavega** [comment]
Closing this as its not an active problem for Neuroscout
