### ISSUE TITLE
fix discrepancies with LTS speech

### ISSUE THREAD

**Issue by adelavega** [neuroscout/neuroscout#763]
Some duration values are 600. Search across all datasets for long speech values.

**Comment by rbroc** [comment]
I've searched for high duration values (>2) for speech regressor across all datasets (in [this PR](https://github.com/neuroscout/neuroscout-reports/pull/25), `diagnostics/odd_durations`)

There are a few cases with values slightly higher than 2 but durations in predictor events match transcripts, so that sounds like a lack of precision in the forced alignment we may not have to worry about.

The major issue is there being a few 600s values for LTS. They are all located in run 1, condition 1 (you can find predictor ids, run nr and onsets [here](https://github.com/neuroscout/neuroscout-reports/blob/979baec236effe6cd5b403dfa856a7d3853ebed1/diagnostics/odd_durations/LTS_odd_durations.tsv). 

I've tried to check if that comes directly from the transcripts, but looking at the tsv files `datasets/raw/ds001545/`, there are no such duration values.
However, it looks like the onsets of the predictor events with high duration exactly match those of a few words in `cond1_run-01.tsv` which have duration 0.0. 

```
     duration   onset  speaker         text
28        0.0   58.02        1           no
62        0.0   68.25        1          cap
63        0.0   68.25        1      anatole
121       0.0   86.32        1       family
181       0.0  161.79        3  information
271       0.0  226.41       10    inaudible
272       0.0  226.41       10       000346
389       0.0  359.79        3  information
390       0.0  359.79        3           of
391       0.0  359.79        3         that
392       0.0  359.79        3         kind
393       0.0  359.79        3        youre
511       0.0  454.24        1           no
545       0.0  464.55        1          cap
546       0.0  464.55        1      anatole
604       0.0  482.56        1       family
```

My guess is that those zeros get filled with a different value at some stage.
May simply be a coincidence, but the maximum onset value in the speech predictor events happens to be `599.9`.

**Comment by adelavega** [comment]
okay, that's great. I'll have to dig into the db to see if those values are there, or get added later somehow

**Comment by adelavega** [comment]
sorry the delay, Ill look at this tomorrow!

**Comment by adelavega** [comment]
Okay, I've replaced the 600 length values for word stimuli (about 5 different stimuli appearing in a total of 135 different places), with the mean duration (0.2).

For all those models with speech related predictors we should be able to re-run reports and recompile and that should fix the predictors.

**Comment by rbroc** [comment]
@adelavega, seems like values have not been updated yet.
Models still pick up on the old duration values, and api also still returns old durations for predictor events.

**Comment by adelavega** [comment]
Weird will look into this
