### ISSUE TITLE
Add format for uploads to frontend

### ISSUE THREAD

**Issue by jsmentch** [neuroscout/neuroscout#794]
I'd like to upload some predictors but don't know the correct format. Would these be a .tsv file with columns for onset, value, duration, etc? Thanks!

**Comment by jsmentch** [comment]
If there were a sample predictor file somewhere I could just base it off of that

**Comment by adelavega** [comment]
Ah, sorry that's a fairly glaring commission.

The format is like BIDS. Tab-delimited files with the following columns
`onset` `duration`, and the remaining columns are named the final predictor name. e.g. `brightness`.

Onset and duration are both in seconds. 

You can denote missing values with the string `n/a`, but be careful because sometimes it's best to just do two separate uploads for predictors that don't align (i.e. if one predictor is sampled at 1hz and the other is at 1.5hz).

Let me know if that all makes sense. I've changed this issue to remind us to add this info.

**Comment by jsmentch** [comment]
Thanks! It seems to have worked, the analysis passed, though I haven't run it yet.

2 things I'm coming across, though neither is really major:
- In the neuroscout web app, the design matrix of an analysis with my uploaded predictors never loads. (Other analysis design matrices loaded fine just now)

- I want to delete the features I uploaded to avoid clutter and replace them with a newer, better version but there is no option to delete. I will just upload a new one with a different name for now.

**Comment by adelavega** [comment]
can you give me an analysis_id for your first problem?

if you give me a collection id i can also delete that for you. adding a delete function could be possible but it's actually a bit tricky because what does that mean for analyses that have been created with those predictors? especially if they are now past the DRAFT stage, and in theory should not be deletable.

an alternative is to upload predictors with the same name, but a new collection name. in theory, having a new predictor with the same name is allow, the interface just shows the latest one with that name. i haven't tested this for uploaded predictors, but that's how it works for normal extracted predictors (so we can keep updating them without deleting old ones).

**Comment by jsmentch** [comment]
for the first issue, analysis id: ArqX8

Ah ok, that makes sense. I think I messed up when I uploaded the predictors and left the collection name field blank. What is the collection name supposed to be or contain? Is this a general title of the predictors or a description? This I guess is another point of confusion I had then in using this.

Here is a screenshot of the predictors
![Screen Shot 2020-07-13 at 2 35 27 PM](https://user-images.githubusercontent.com/20958589/87340864-aa940080-c516-11ea-9bd1-232024499958.png)

**Comment by adelavega** [comment]
ah, good to know, it should not let you leave it blank.

it's just a name to give to that set you're uploading. it can be anything. hopefully descriptive.

**Comment by adelavega** [comment]
okay, i'm seeing this error for reports for that ID:

are you using the API to get these reports?

worker_1      | [2020-07-13 18:33:52,613: ERROR/ForkPoolWorker-16] Task workflow.generate_report[0c4e6ef3-62ff-442e-864b-b166c6c40c92] raised unexpected: TypeError("generate_report() missing 3 required positional arguments: 'run_ids', 'sampling_rate', and 'scale'",)
worker_1      | Traceback (most recent call last):
worker_1      |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task
worker_1      |     R = retval = fun(*args, **kwargs)
worker_1      |   File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__
worker_1      |     return self.run(*args, **kwargs)
worker_1      |   File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 155, in _inner
worker_1      |     reraise(*exc_info)
worker_1      |   File "/usr/local/lib/python3.6/site-packages/sentry_sdk/_compat.py", line 57, in reraise
worker_1      |     raise value
worker_1      |   File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 150, in _inner
worker_1      |     return f(*args, **kwargs)
worker_1      | TypeError: generate_report() missing 3 required positional arguments: 'run_ids', 'sampling_rate', and 'scale'


This looks unrelated and is actually a bug I introduced, so I'll fix that!

**Comment by adelavega** [comment]
A related bug is that this should have failed and not just stayed pending, so need to figure out what's up with that

**Comment by jsmentch** [comment]
ok, thanks! Nope, with this I was just using the web interface

**Comment by jsmentch** [comment]
I've tested uploading new features with a different collection name and it looks like both collections are visible for me and the old versions are not overwritten see screenshot:

<img width="792" alt="Screen Shot 2020-07-14 at 12 21 43 PM" src="https://user-images.githubusercontent.com/20958589/87450750-eab5ba80-c5cc-11ea-8abe-942a35c2826a.png">

**Comment by adelavega** [comment]
That makes sense actually. The frontend is using a different mechanism for shown you your private collections, so this is expected behavior (for now).

If these were to be public, other people would only see the newest version.
