### ISSUE TITLE
reports fail if subjects' runs mismatch (pybids limitation) 

### ISSUE THREAD

**Issue by jdkent** [neuroscout/neuroscout#821]
Review section (Design Reports)

for the Life dataset, when I added subject rid0000005 run - 2, I got an error on the page:

Report failed to generate
[Error validating analysis, `rms`](https://youtu.be/VWUGOEgAsSQ?t=1326)

don't know if this is just a small idiosyncratic error for this participant or something larger.

**Comment by adelavega** [comment]
The problem is that pybids entities used to require a design matrix are: subject 1 and 5, run 1 and 2, but report is for subject 1 run 1, subject 5, run 2. So only two runs event's are generated, and pybids is expecting 4 runs of events. 

We need a way to specify to pybids to only generate models for those two specific runs, not all combinations of runs and subjects. 

One option would be to loop over runs outside of pybids when generating models / plots.

**Comment by adelavega** [comment]
@rwblair there is also a bug here in which the frontend shows a previous report even though the current report has failed. 

We requested 3 runs, but it failed (due to pybids), however the frontend still shows a previous report (which is for subject 1 run 1 and 2). However, the runs are titled wrong (subject 1 run 1, subject 5 run 2). Some logic which matches the results to the run entities must be failing in this edge case. 


![Screenshot from 2020-10-08 16-03-09](https://user-images.githubusercontent.com/2774448/95513466-050af480-0980-11eb-894e-aeb56d8135c8.png)

**Comment by adelavega** [comment]
I also think we should move the errors to be above the DM (so they dont go unnoticed)
